import { createRoot } from "react-dom/client";
import App from "./App.tsx";
import "./index.css";
import { registerSW } from "virtual:pwa-register";

// automatically register the service worker generated by vite-plugin-pwa
const updateSW = registerSW({
  onUpdate() {
    if (confirm("New content is available, reload to update?")) {
      window.location.reload();
    }
  }
});

createRoot(document.getElementById("root")!).render(<App />);
